package kr.co.gamja.study_hub.feature.studypage

import androidx.lifecycle.ViewModel

class RelativeMajorFragmentViewModel : ViewModel() {
    fun setUserMajor(item: String) {
        when (item) {
            "공연예술과" -> CreateStudyInfo.relativeMajor = "PERFORMING_ART"
            "IBE전공" -> CreateStudyInfo.relativeMajor = "IBE"
            "건설환경공학" -> CreateStudyInfo.relativeMajor = "CIVIL_AND_ENVIRONMENTAL_ENGINEERING"
            "건축공학" -> CreateStudyInfo.relativeMajor = "ARCHITECTURAL_ENGINEERING"
            "경영학부" -> CreateStudyInfo.relativeMajor = "BUSINESS_ADMINISTRATION"
            "경제학과" -> CreateStudyInfo.relativeMajor = "ECONOMICS"
            "국어교육과" -> CreateStudyInfo.relativeMajor = "KOREAN_LANGUAGE_EDUCATION"
            "국어국문학과" -> CreateStudyInfo.relativeMajor = "KOREAN_LANGUAGE_LITERATURE"
            "기계공학과" -> CreateStudyInfo.relativeMajor = "MECHANICAL_ENGINEERING"
            "데이터과학과" -> CreateStudyInfo.relativeMajor = "BUSINESS_DATA_SCIENCE"
            "도시건축학" -> CreateStudyInfo.relativeMajor = "ARCHITECTURE_AND_URBAN_DESIGN"
            "도시공학과" -> CreateStudyInfo.relativeMajor = "URBAN_ENGINEERING"
            "도시행정학과" -> CreateStudyInfo.relativeMajor = "URBAN_POLICY_AND_ADMINISTRATION"
            "독어독문학과" -> CreateStudyInfo.relativeMajor = "GERMAN_LANGUAGE_LITERATURE"
            "동북아통상전공" -> CreateStudyInfo.relativeMajor = "SCHOOL_OF_NORTHEAST_ASIAN"
            "디자인학부" -> CreateStudyInfo.relativeMajor = "DESIGN"
            "무역학부" -> CreateStudyInfo.relativeMajor = "INTERNATIONAL_TRADE"
            "문헌정보학과" -> CreateStudyInfo.relativeMajor = "LIBRARY_AND_INFORMATION"
            "물리학과" -> CreateStudyInfo.relativeMajor = "PHYSICS"
            "미디어커뮤니케이션학과" -> CreateStudyInfo.relativeMajor = "MASS_COMMUNICATION"
            "바이오-로봇 시스템 공학과" -> CreateStudyInfo.relativeMajor =
                "MECHANICAL_ENGINEERING_AND_ROBOTICS"
            "법학부" -> CreateStudyInfo.relativeMajor = "LAW"
            "불어불문학과" -> CreateStudyInfo.relativeMajor = "FRENCH_LANGUAGE_LITERATURE"
            "사회복지학과" -> CreateStudyInfo.relativeMajor = "SOCIAL_WELFARE"
            "산업경영공학과" -> CreateStudyInfo.relativeMajor = "INDUSTRIAL_AND_MANAGEMENT_ENGINEERING"
            "생명공학부(나노바이오공학전공)" -> CreateStudyInfo.relativeMajor = "NANO_BIO_ENGINEERING"
            "생명공학부(생명공학전공)" -> CreateStudyInfo.relativeMajor = "BIO_ENGINEERING"
            "생명과학부(분자의생명전공)" -> CreateStudyInfo.relativeMajor = "MOLECULAR_MEDICAL_SCIENCE"
            "생명과학부(생명과학전공)" -> CreateStudyInfo.relativeMajor = "BIOLOGICAL_SCIENCE"
            "서양화전공" -> CreateStudyInfo.relativeMajor = "WESTERN_PAINTING"
            "세무회계학과" -> CreateStudyInfo.relativeMajor = "TAX_ACCOUNTING"
            "소비자학과" -> CreateStudyInfo.relativeMajor = "CONSUMER_SCIENCE"
            "수학과" -> CreateStudyInfo.relativeMajor = "MATHEMATICS"
            "수학교육과" -> CreateStudyInfo.relativeMajor = "MATHEMATICS_EDUCATION"
            "스마트물류공학전공" -> CreateStudyInfo.relativeMajor = "SMART_LOGISTICS_ENGINEERING"
            "스포츠과학부" -> CreateStudyInfo.relativeMajor = "SPORT_SCIENCE"
            "신소재공학과" -> CreateStudyInfo.relativeMajor = "MATERIALS_SCIENCE_ENGINEERING"
            "안전공학과" -> CreateStudyInfo.relativeMajor = "SAFETY_ENGINEERING"
            "에너지화학공학" -> CreateStudyInfo.relativeMajor = "ENERGY_CHEMICAL_ENGINEERING"
            "역사교육과" -> CreateStudyInfo.relativeMajor = "HISTORY_EDUCATION"
            "영어교육학과" -> CreateStudyInfo.relativeMajor = "ENGLISH_LANGUAGE_EDUCATION"
            "영어영문학과" -> CreateStudyInfo.relativeMajor = "ENGLISH_LANGUAGE_LITERATURE"
            "운동건강학부" -> CreateStudyInfo.relativeMajor = "HEALTH_KINESIOLOGY"
            "유아교육과" -> CreateStudyInfo.relativeMajor = "EARLY_CHILDHOOD_EDUCATION"
            "윤리교육과" -> CreateStudyInfo.relativeMajor = "ETHICS_EDUCATION"
            "일본지역문화학과" -> CreateStudyInfo.relativeMajor = "JAPANESE_LANGUAGE_LITERATURE"
            "일어교육과" -> CreateStudyInfo.relativeMajor = "JAPANESE_LANGUAGE_EDUCATION"
            "임베디드시스템공학과" -> CreateStudyInfo.relativeMajor = "EMBEDDED_SYSTEM_ENGINEERING"
            "전기공학과" -> CreateStudyInfo.relativeMajor = "ELECTRICAL_ENGINEERING"
            "전자공학과" -> CreateStudyInfo.relativeMajor = "INFORMATION_TELECOMMUNICATION_ENGINEERING"
            "정보통신학과" -> CreateStudyInfo.relativeMajor = "Information Telecommunication Engineering"
            "정치외교학과" -> CreateStudyInfo.relativeMajor = "POLITICAL_INTERNATIONAL"
            "중어중문학과" -> CreateStudyInfo.relativeMajor = "CHINESE_LANGUAGE_LITERATURE"
            "창의인재개발학과" -> CreateStudyInfo.relativeMajor = "CREATIVE_HUMAN_RESOURCE_DEVELOPMENT"
            "체육교육과" -> CreateStudyInfo.relativeMajor = "PHYSICAL_EDUCATION"
            "컴퓨터공학부" -> CreateStudyInfo.relativeMajor = "COMPUTER_SCIENCE_ENGINEERING"
            "테크노경영학과" -> CreateStudyInfo.relativeMajor = "TECHNOLOGY_MANAGEMENT"
            "패션산업학과" -> CreateStudyInfo.relativeMajor = "FASHION_INDUSTRY"
            "한국화전공" -> CreateStudyInfo.relativeMajor = "KOREAN_PAINTING"
            "해양학과" -> CreateStudyInfo.relativeMajor = "MARINE_SCIENCE"
            "행정학과" -> CreateStudyInfo.relativeMajor = "PUBLIC_ADMINISTRATION"
            "화학과" -> CreateStudyInfo.relativeMajor = "CHEMISTRY"
            "환경공학" -> CreateStudyInfo.relativeMajor = "ENVIRONMENTAL_ENGINEERING"
            else -> CreateStudyInfo.relativeMajor = null
        }

    }
}